info:
  contact: {}
paths:
  /auth/google/callback:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Handle Google Callback for SSO Access Token
  /auth/google/login:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Handle Google Login with SSO
  /auth/logout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Logout handler
  /auth/refresh:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Refresh token rotation handler
  /healthCheck:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: API Health Check
  /me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Admin Check
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Post to Me Check
swagger: "2.0"
