definitions:
  handler.BioRequest:
    properties:
      about_me:
        type: string
      address:
        type: string
      contact:
        $ref: '#/definitions/handler.ContactDTO'
      name:
        type: string
    type: object
  handler.ContactDTO:
    properties:
      email:
        type: string
      github:
        type: string
      instagram:
        type: string
      linkedin:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/{provider}/callback:
    get:
      consumes:
      - application/json
      parameters:
      - description: OAuth provider
        enum:
        - google
        - github
        in: path
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Callback handler
  /auth/{provider}/login:
    get:
      consumes:
      - application/json
      parameters:
      - description: OAuth provider
        enum:
        - google
        - github
        in: path
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Login handler
  /auth/logout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Logout handler
  /auth/refresh:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Refresh Token handler
  /bio:
    delete:
      responses: {}
      summary: Delete Bio
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Get Bio
    post:
      consumes:
      - application/json
      parameters:
      - description: Bio update payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.BioRequest'
      produces:
      - application/json
      responses: {}
      summary: Upsert Bio (create and update)
  /healthCheck:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: API Health Check
swagger: "2.0"
