info:
  contact: {}
paths:
  /auth/{provider}/callback:
    get:
      consumes:
      - application/json
      parameters:
      - description: OAuth provider
        enum:
        - google
        - github
        in: path
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Callback handler
  /auth/{provider}/login:
    get:
      consumes:
      - application/json
      parameters:
      - description: OAuth provider
        enum:
        - google
        - github
        in: path
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Login handler
  /auth/logout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Logout handler
  /auth/refresh:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Refresh Token handler
  /healthCheck:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: API Health Check
  /me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Admin Check
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Post to Me Check
swagger: "2.0"
